apiVersion: v1
kind: Service
metadata:
  name: {{ include "datawiza-access-broker.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 9772
      targetPort: 9772
  selector:
    app: datawiza-access-broker